osx_image: xcode10
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/UIDeviceIcon.xcworkspace -scheme UIDeviceIcon-Example -sdk iphonesimulator12.0 -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.0' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
